name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies (Client)
      working-directory: ./client
      run: npm ci

    - name: Install Dependencies (Server)
      working-directory: ./server
      run: npm ci

    - name: Lint
      run: |
        cd client && npm run lint
        cd ../server && npm run lint

    - name: Test
      run: |
        cd client && npm test
        cd ../server && npm test

    - name: Build
      run: |
        cd client && npm run build
        cd ../server && npm run build

    - name: Docker Build
      if: github.ref == 'refs/heads/main'
      run: docker build -t pulse-app -f docker/Dockerfile .